# Generated by Django 2.1.3 on 2018-11-28 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(verbose_name='date of creation')),
            ],
            options={
                'verbose_name_plural': 'Achievements',
                'verbose_name': 'Achievement',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(verbose_name='date of creation')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('year_at_school', models.IntegerField()),
                ('date_created', models.DateTimeField(verbose_name='date of creation')),
                ('achievements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='main.Achievements')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.Category')),
            ],
        ),
    ]
